### ISSUE TITLE
OnSignatureChange Issue

### ISSUE THREAD

**Issue by rockydant** [Mobsites/Blazor.SignaturePad#18]
Hello,

I really love this component and trying to apply into my pet project. However whenever I tried to call OnSignatureChange I got this issue? I tried to check around like reference the bundle.js after any framework js lib but no joy. I am using Blazor Server latest version as well as latest version of Signature Pad.

Anyone meet this issue?

blazor.server.js:19 [2020-11-26T01:51:26.398Z] Error: Microsoft.JSInterop.JSException: Cannot read property 'update' of undefined
TypeError: Cannot read property 'update' of undefined
    at Object.update (http://localhost:44357/_content/Mobsites.Blazor.SignaturePad/bundle.js:5:12077)
    at http://localhost:44357/_framework/blazor.server.js:1:70043
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:44357/_framework/blazor.server.js:1:70009)
    at http://localhost:44357/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:44357/_framework/blazor.server.js:1:26263)
    at e.processIncomingData (http://localhost:44357/_framework/blazor.server.js:1:24201)
    at e.connection.onreceive (http://localhost:44357/_framework/blazor.server.js:1:17286)
    at WebSocket.i.onmessage (http://localhost:44357/_framework/blazor.server.js:1:46503)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Mobsites.Blazor.SignaturePad.Update()
   at Mobsites.Blazor.SignaturePad.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by allan-mobley-jr** [comment]
Unfortunately, I have not had time to update this component to use the latest Blazor release.

I'm sure there were some breaking changes from early Blazor 3.1 to the now .Net 5 release.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rockydant** [comment]
Thank you!

**Comment by rockydant** [comment]
I found the root cause with my application. Seems it did conflict  when I initiated it along with one of my objects so the DOM did not completed rendering. Confirm the component work properly with current version of Blazor (.NET 5)

**Comment by allan-mobley-jr** [comment]
Okay, cool. After the new year, I plan on updating this component to use the latest along with is and css isolation.

Currently, swamped with the day job lol.

Thanks for using it as well as your feedback.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by angelru** [comment]
Any update?

**Comment by hdamis** [comment]
Any update? to work on .Net 5.

**Comment by hdamis** [comment]
I install visual studio 2022 and it works fine on .net core 6
