### ISSUE TITLE
Error on first load "Could not find 'Mobsites.Blazor.SignaturePads.init'"

### ISSUE THREAD

**Issue by Matthewsre** [Mobsites/Blazor.SignaturePad#27]
# Configuration
I am trying to add version **1.1.7** to a net5.0 project that is WebAssembly hosted. (AspNetCore PackageReferences are 5.0.4)

In the **index.html** file:

- CSS is loaded in the head section
- JavaScript is loaded after the _framework files before the closing </body> tag

Copy/Paste usage of the component:

```
        <SignaturePad @ref="_signaturePad"
                      MinHeight="200"
                      MaxHeight="200"
                      OnSignatureChange="@OnSignatureChange">
            <SignaturePadFooter>
                <SignaturePadClear>
                    <RadzenIcon Icon="clear" />
                </SignaturePadClear>
                <SignaturePadUndo>
                    <RadzenIcon Icon="undo" />
                </SignaturePadUndo>
            </SignaturePadFooter>
        </SignaturePad>
```

# Problem

Going into debug I land on the home page and see that the javascript has loaded

![image](https://user-images.githubusercontent.com/2955659/114795466-72d71500-9d43-11eb-9399-6d8f872762f6.png)

When I click on the left nav to the page with the signature I get the following error:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'Mobsites.Blazor.SignaturePads.init' ('Mobsites' was undefined).
      Error: Could not find 'Mobsites.Blazor.SignaturePads.init' ('Mobsites' was undefined).
          at https://localhost:44367/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44367/_framework/blazor.webassembly.js:1:1247)
          at b (https://localhost:44367/_framework/blazor.webassembly.js:1:2989)
          at https://localhost:44367/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44367/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44367/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44367/_framework/dotnet.5.0.5.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'Mobsites.Blazor.SignaturePads.init' ('Mobsites' was undefined).
Error: Could not find 'Mobsites.Blazor.SignaturePads.init' ('Mobsites' was undefined).
    at https://localhost:44367/_framework/blazor.webassembly.js:1:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44367/_framework/blazor.webassembly.js:1:1247)
    at b (https://localhost:44367/_framework/blazor.webassembly.js:1:2989)
    at https://localhost:44367/_framework/blazor.webassembly.js:1:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44367/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44367/_framework/blazor.webassembly.js:1:64232)
    at _mono_wasm_invoke_js_blazor (https://localhost:44367/_framework/dotnet.5.0.5.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Mobsites.Blazor.SignaturePad.Initialize()
   at Mobsites.Blazor.SignaturePad.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Here is a screenshot of the page/error:

![image](https://user-images.githubusercontent.com/2955659/114795681-03155a00-9d44-11eb-8d6a-e2f209b1d990.png)

If I click refresh on the page it works just fine:

![image](https://user-images.githubusercontent.com/2955659/114795795-4d96d680-9d44-11eb-8314-290f6aa1342f.png)

I can reproduce this every time I load the page, even though I can see the script has already loaded before going to the page.

Any guidance for this issue?

**Comment by NGE2015** [comment]
I'm also having the same issue with the last version.
On Chrome it works, edge doesnt .

Edge doesnt work when its on Debug Mode.
